version: '3'

services:
  database:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - papir-db:/var/lib/postgresql/data

  database-test:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5431:5432

volumes:
  papir-db:
