name: Type checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Run type-checking
      - run: npm run ci:tsc
